In [1]:
import sys
import os
import json
import utils
sys.path.append('c:\\Users\\yurou\\Desktop\\Master thesis\\Non-parametric-Learning-of-DAG-by-RKHS\\Final')
from RKHS import RKHS_DAGMA_extractj
import sys
from notears import NotearsMLP, notears_nonlinear, NotearsSobolev, notears_linear
import torch
import numpy as np
import json
import argparse

In [2]:
def random_function(index, x):
    if index == 0:
        return np.exp(-np.abs(x))
    elif index == 1:
        return 0.5*(x**2)
    else:
        return np.sin(x)

In [12]:
X = np.array([[1,2,3], [4, 5, 6]]) #[2, 3]
print(X)
index = np.random.randint(0, 3, size = X.shape[1])
for i in range(X.shape[1]):
    print(random_function(index[i], X[:, i]))

[[1 2 3]
 [4 5 6]]
[0.36787944 0.01831564]
[ 0.90929743 -0.95892427]
[ 4.5 18. ]


In [22]:
np.exp(-4)

0.01831563888873418

In [23]:
np.sin(2)

0.9092974268256817

In [25]:
0.5*(3)**2

4.5

In [13]:
sum(random_function(index[i], X[:, i]) for i in range(X.shape[1])) 

array([ 5.77717687, 17.05939136])

In [3]:
n, d, s0, graph_type, sem_type = 100, 10, 40, 'ER', 'gp' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 0.64789949 -0.97113082 -0.35848423 -1.37633536 -0.08767307  1.36926015
   1.50514331  1.26437548 -1.64913922  1.33337183]
 [ 0.0799723  -0.14893914  0.70181711 -2.48750177  1.36687937 -0.22282321
  -0.11458819 -0.24364085 -0.01913398  0.39726431]
 [ 0.30472722  0.26541096  0.91048418  0.31372584  1.1253141  -2.81856114
   0.10533727 -0.92600217  0.25001851 -0.734439  ]
 [-1.04238382  0.20074044 -0.52335294 -2.26375144 -0.35899555 -1.25809096
  -0.38688355 -2.17805065 -0.59103917 -0.26755527]
 [ 1.73763691  2.14905672  1.46489057  3.0199957   1.2206081  -0.9806283
  -0.34204001  0.46373377  1.75703859  0.34429833]
 [-1.8857701   0.14603525 -2.15896825  1.69107599 -1.33949555  1.29875007
   1.01637284 -1.12741949  1.71357421  2.1133121 ]
 [-0.60640924  1.48893744  1.27011248 -0.33523038  0.42837337  1.28355659
   1.03693145  0.35055414  0.45865642 -1.85066635]
 [-1.02505722 -0.39418655 -1.28429668 -0.67624996 -0.12346315 -0.9132688
   0.01164256 -2.5961626   2.12908168  0.77199226]
 [

In [4]:
n, d, s0, graph_type, sem_type = 100, 10, 40, 'ER', 'combi' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 1.58681359e+00  2.62758753e+00  3.96444647e+00  3.18554646e+00
  -8.76730672e-02  4.25081251e+00  1.16737375e+00  1.71684317e+00
   1.56654710e+00  5.04731603e+00]
 [ 1.99224964e-01  2.29977572e+00 -1.18720072e-02  3.13969707e-01
   1.36687937e+00  4.29179519e+00 -5.48035265e-01  7.29859555e-01
  -1.84615778e+00 -1.12811609e+00]
 [ 1.62893866e+00  2.94765549e+00  4.60324609e+00  2.41902986e+00
   1.12531410e+00  2.20567190e+00  8.17642332e-01  8.15391545e-02
   1.49932479e+00  2.33071053e+00]
 [ 1.69346650e+00  1.15802886e+00  2.40301741e+00 -5.39167856e-01
  -3.58995552e-01  8.68806750e-01  9.58631349e-01 -1.84467395e+00
   1.05584298e+00  2.18356900e+00]
 [ 6.76019851e-01  2.55901331e+00  7.48167206e-01  1.72208684e-02
   1.22060810e+00  3.96910168e+00 -5.95427561e-01  1.46348410e+00
   9.97248540e-01  1.98933508e+00]
 [ 1.00288199e+00  1.92088518e+00  2.46355874e+00 -1.34106735e+00
  -1.33949555e+00  3.12459714e+00 -5.18325154e-01 -6.28255853e-01
   1.57841294e+00 -7.26426080e-01

In [2]:
n, d, s0, graph_type, sem_type = 100, 10, 40, 'ER', 'kernel' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 1.89915808e+00  3.88745945e-01  2.21847601e+00  1.01887096e+00
  -8.76730672e-02  1.31580414e+00  1.94953769e+00  2.80404036e+00
   1.74187161e+00  2.24901357e+00]
 [ 1.86985316e+00  1.59722011e+00 -5.26280898e-01  1.35642711e+00
   1.36687937e+00  2.26717775e+00 -1.83199832e-01  7.45431082e-01
   1.34680104e+00  4.03138119e-02]
 [ 2.85487598e-01  1.21844654e-01  1.67192139e+00 -8.18387967e-01
   1.12531410e+00  1.46243886e+00  1.08984253e+00  1.75921753e-01
  -7.72580411e-01 -2.23396061e-01]
 [ 6.32610322e-01  3.93911799e-01  5.84289972e-01  1.44046720e+00
  -3.58995552e-01  3.73455191e+00  2.85344040e-01 -4.94637124e-01
   1.34944220e+00  2.66560506e+00]
 [-1.11730322e+00  6.73070982e-01  7.19517290e-01  8.04519696e-01
   1.22060810e+00  8.84324145e-01  1.04400889e+00  1.52025270e+00
   1.80145902e+00  2.94696042e+00]
 [-1.13504063e-01 -1.17465395e+00  6.83205327e-01  1.23357027e+00
  -1.33949555e+00  1.22137124e+00 -3.68560408e-01  1.33568879e+00
   1.03824473e+00 -1.94715297e-01

In [5]:
n, d, s0, graph_type, sem_type = 100, 20, 80, 'ER', 'gp' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 0.92802027 -0.49095782 -1.00905964 ... -0.64475925  1.18267054
   1.42575515]
 [-2.7618692  -0.29439913 -2.11649758 ...  0.54341112 -2.49444601
   0.84584151]
 [-1.11307238  1.53481361 -1.77073738 ...  0.39473603  0.69451601
  -0.66420275]
 ...
 [-2.40319176 -0.32892382  1.49032432 ... -0.22592731  0.60263498
   0.51430232]
 [ 1.89104287  2.12068388  0.68992886 ...  0.57614475  0.79009609
  -0.09714756]
 [-1.33807769 -0.16503171 -1.24255724 ... -0.76238611 -1.2874328
  -0.03304323]]
4.367020768356702
-4.944543557046831


In [6]:
n, d, s0, graph_type, sem_type = 100, 20, 80, 'ER', 'combi' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 1.15076224  7.69596671  6.18693986 ...  1.6331463   0.6751031
   1.22044044]
 [ 0.63638415  3.51239304  4.5615154  ...  3.6571687   1.96709033
   2.2379839 ]
 [ 0.74480368  2.01581348  4.50598869 ...  0.93637076  3.15425262
  -1.11069874]
 ...
 [ 1.20945238  1.32833868  3.44288928 ...  0.81646648  3.23960519
   0.09928242]
 [ 2.79080382  3.76211117 -3.07497076 ...  1.41998389  0.70312242
   1.1763111 ]
 [ 0.0240985   5.40686291  5.213224   ...  1.27562188  0.81367626
   2.55653398]]
8.587485681105047
-4.421549953788329


In [3]:
n, d, s0, graph_type, sem_type = 100, 20, 80, 'ER', 'kernel' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 1.88189424 -0.10097284  0.97377949 ...  1.49348543  1.94757593
   1.95878077]
 [ 0.32633747  0.49176748  0.87271357 ...  2.22657019  0.26323507
   1.43119479]
 [ 1.87999205  1.73919882  0.00268083 ...  0.7026303   0.22188011
   0.87062481]
 ...
 [-0.51387152  0.07669153  0.56511913 ...  0.17377222  0.68890232
   2.40343751]
 [ 0.49718204  0.181156    1.5222099  ...  1.37377818  2.22939538
   0.29202715]
 [ 1.560234    0.52515836 -0.1724287  ... -0.14423979 -1.11785766
   1.29195269]]
4.173705182955345
-2.5529898158340787


In [7]:
n, d, s0, graph_type, sem_type = 100, 30, 120, 'ER', 'gp' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[-0.4157447   0.6461898   0.59706078 ...  0.60205661 -0.20201258
  -0.09519928]
 [-0.52451219 -2.31154434  0.39788559 ... -1.50857505 -1.65582451
  -0.22772779]
 [ 0.81310127 -1.24710812 -0.05317512 ...  0.33313533  0.16533493
   0.43243668]
 ...
 [-0.10569679  0.94246511 -1.416249   ... -0.24956062 -1.8756508
   1.34614637]
 [ 0.74279571 -2.27887517  1.38189687 ...  0.45022552  0.22850511
   0.23704865]
 [-0.75498153 -0.52175731  1.11426976 ... -1.90772532 -1.83434101
   0.0204918 ]]
5.3723414950002635
-4.627629592037502


In [8]:
n, d, s0, graph_type, sem_type = 100, 30, 120, 'ER', 'combi' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[-0.4157447   0.62619651  4.50622125 ...  0.99648213 -0.35991085
  -0.09519928]
 [-0.52451219 -0.13410024  1.64624352 ...  0.6754416  -1.173735
  -0.22772779]
 [ 0.81310127  1.23008524  2.95567918 ... -0.44331153  2.22934027
   0.43243668]
 ...
 [-0.10569679  2.26971557  4.35772706 ...  2.29674954  1.51321681
   1.34614637]
 [ 0.74279571  0.43031108  2.94257451 ...  0.81210132 -0.30771564
   0.23704865]
 [-0.75498153  2.29270223  1.52100951 ...  2.00260573 -1.35889953
   0.0204918 ]]
6.484361145467108
-3.8551436480359516


In [4]:
n, d, s0, graph_type, sem_type = 100, 30, 120, 'ER', 'kernel' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[-0.4157447   1.30973247 -1.41471469 ...  0.30968329  2.65021395
  -0.09519928]
 [-0.52451219  2.24477524  3.10925499 ...  0.96627044  1.31107251
  -0.22772779]
 [ 0.81310127  3.95425614  0.55145677 ...  1.5738002   2.10827553
   0.43243668]
 ...
 [-0.10569679 -0.47616113  0.97577324 ...  0.3330013   1.61510249
   1.34614637]
 [ 0.74279571  1.41062307  1.41260701 ... -0.08770842  0.11892607
   0.23704865]
 [-0.75498153  0.8742069   0.7513852  ...  2.23020797 -0.68822051
   0.0204918 ]]
4.2239720681450015
-3.0051281618157635


In [9]:
n, d, s0, graph_type, sem_type = 100, 40, 160, 'ER', 'gp' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 3.99021374 -0.32511252 -2.18007435 ... -4.52759409 -0.83778609
  -0.04609665]
 [ 2.22208588  1.1365076  -1.03347289 ... -0.34938535  0.32153868
   1.87138487]
 [-0.38684996 -3.37297087  0.02639003 ... -0.37351846 -1.68385545
  -0.57888632]
 ...
 [ 2.84077762 -0.76991884  0.68282907 ...  0.18245     1.27086148
  -0.81783364]
 [ 2.25313318 -1.10575912 -2.77288281 ... -0.52636257  1.05326198
   0.26581187]
 [ 2.26251418 -1.27543394 -0.12018933 ... -1.1154778  -0.56916015
  -1.18686882]]
6.129942137554348
-4.941251950968081


In [10]:
n, d, s0, graph_type, sem_type = 100, 40, 160, 'ER', 'combi' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 0.9974834   1.55765797  4.80287467 ...  3.45316939  2.74070609
   0.80111077]
 [ 1.66083998  0.15552914  3.66756367 ...  1.43869357  3.56935362
   0.92246987]
 [ 0.06027933  1.56672193  0.10790891 ...  0.90879142  2.45814671
  -1.62422646]
 ...
 [ 0.45420687 -0.44600555  3.20836998 ...  4.37323598  0.34872544
  -0.84884384]
 [ 2.16733644  0.42107537  3.38383407 ...  0.79033785  4.24611692
  -0.6012243 ]
 [-0.52239232  0.2429037   1.75390563 ... -0.15331712  2.79356188
   1.28263346]]
7.325786460439188
-3.875190700536924


In [5]:
n, d, s0, graph_type, sem_type = 100, 40, 160, 'ER', 'kernel' 
utils.set_random_seed(0)
torch.manual_seed(0)
B_true = utils.simulate_dag(d, s0, graph_type)
X = utils.simulate_nonlinear_sem(B_true, n, sem_type)
print(X)
print(np.max(X))
print(np.min(X))

[[ 2.19578431  2.10207184  1.13159302 ...  0.78260205 -0.88425566
   1.39126377]
 [ 2.59504565  0.41322187  0.11926707 ...  2.40129341  1.74972053
   1.27604856]
 [ 0.39483149 -0.85672764  0.3065443  ...  1.82832167  0.90097217
   1.06533206]
 ...
 [ 1.38133643 -0.23286202  3.12611332 ...  1.0203368  -0.23763019
   1.09917327]
 [ 1.846035    1.51542811  2.34884459 ...  0.674805    1.23853805
   2.04303931]
 [ 0.94863388  1.39676022  2.22865507 ...  0.3173584   3.84026455
  -1.10859287]]
4.297964804272956
-3.514768119101935


In [2]:
torch.set_default_dtype(torch.double)

torch.backends.cudnn.benchmark = False

torch.use_deterministic_algorithms(True)

In [10]:
def squared_loss(output, target):
    n = target.shape[0]
    loss = 0.5 / n * torch.sum((output - target) ** 2)
    return loss


def NOTEARS_MLP(X, B_true, function_type, d, seed):
    results = {}
    model = NotearsMLP(dims=[d, 10, 1], bias=True)
    W_est, output = notears_nonlinear(model, X, lambda1=2e-2)
    acc = utils.count_accuracy(B_true, W_est != 0)
    diff = np.linalg.norm(W_est - abs(B_true))
    X_torch = torch.from_numpy(X)
    x_est = model.forward(X_torch)
    mse = squared_loss(x_est, X_torch)
    h_val = model.h_func().detach().cpu().numpy()
    filename = f'NOTEARS_MLP_function_type_{function_type}_d{d}_seed{seed}'
    results = {
    'SHD': acc['shd'],
    'TPR': acc['tpr'],
    'F1': acc['f1'],
    'diff': diff,
    'mse': mse.item(),
    'h_val': h_val.item(),
    'W_est': W_est.tolist(),
    'B_true': B_true.tolist(),
    'X': X.tolist()}

    with open(filename, 'w') as file:
        json.dump(results, file, indent=4) 


def NOTEARS_SOB(X, B_true, function_type, d, seed):
    results = {}
    model = NotearsMLP(dims=[d, 10, 1], bias=True)
    W_est, output = notears_nonlinear(model, X, lambda1=2e-2)
    acc = utils.count_accuracy(B_true, W_est != 0)
    diff = np.linalg.norm(W_est - abs(B_true))
    X_torch = torch.from_numpy(X)
    x_est = model.forward(X_torch)
    mse = squared_loss(x_est, X_torch)
    h_val = model.h_func().detach().cpu().numpy()
    filename = f'NOTEARS_MLP_function_type_{function_type}_d{d}_seed{seed}'
    results = {
    'SHD': acc['shd'],
    'TPR': acc['tpr'],
    'F1': acc['f1'],
    'diff': diff,
    'mse': mse.item(),
    'h_val': h_val.item(),
    'W_est': W_est.tolist(),
    'B_true': B_true.tolist(),
    'X': X.tolist()}

    with open(filename, 'w') as file:
        json.dump(results, file, indent=4) 

In [11]:
import os

# Current directory where the script is running
current_directory = os.getcwd()

# Relative path to the file
relative_path = 'T7'

# Full path to the file
full_path = os.path.join(current_directory, relative_path)
full_path

'c:\\Users\\yurou\\Desktop\\Master thesis\\Non-parametric-Learning-of-DAG-by-RKHS\\Final\\experiments\\T7'

In [5]:
import json
import numpy as np
from concurrent.futures import ProcessPoolExecutor

def process_NOTEARS_MLP(d, seed):
    function_type = 'gp'
    filename = f'RKHS_function_type_{function_type}_d{d}_seed{seed}'
    file_path = os.path.join(full_path, filename)
    with open(file_path, 'r') as file:
        data = json.load(file)
        B_true = np.array(data['B_true'])
        X = np.array(data['X'])
    
    # Call the NOTEARS_MLP function (assumed to be defined elsewhere)
    NOTEARS_MLP(X, B_true, function_type, d, seed)


In [6]:
process_NOTEARS_MLP(10, 0)

KeyboardInterrupt: 